--- 
abstract: Validate all data before submitting to your database.
author: 
  - Aran C. Deltac <bluefeet@cpan.org>
build_requires: 
  DBD::SQLite: 1.11
  DateTime::Format::MySQL: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Validation
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Data::FormValidator: 0
requires: 
  DBIx::Class: 0.07005
  FormValidator::Simple: 0.17
  perl: 5.8.1
tests: t/*.t t/*/*.t
version: 0.02002
